import type { Metadata } from 'next'
import Navbar from '@/components/landing/Navbar'
import Footer from '@/components/landing/Footer'

export const metadata: Metadata = {
  title: 'Privacy Policy — Aeros',
  description: 'Learn how Aeros collects, uses, and protects your personal information across our marketplace, operating system, AI, and hardware.',
}

const sections = [
  {
    title: '1. Information We Collect',
    content: [
      {
        heading: 'Information you provide to us',
        body: 'We collect information you provide directly to us, including when you create an account, subscribe to a plan, list or purchase on our marketplace, contact us for support, apply to our partner programs, or otherwise interact with our Services. This may include your name, email address, phone number, business name, role, billing and tax information, and any other information you choose to provide.',
      },
      {
        heading: 'Marketplace and transaction data',
        body: 'When you buy or sell through the Aeros marketplace, we collect information needed to facilitate the transaction, including order details, requests for quotation (RFQs), quotes, catalog listings, pricing, shipping and billing addresses, GST and other tax identifiers, resale or compliance certificates, and payment confirmation data. We collect this both from you and from the counterparties you transact with.',
      },
      {
        heading: 'Lead and application data',
        body: 'When you request a demo, fill out a contact or partner-application form, or share your details with us at a trade show or industry event, we collect the contact and business information you submit so we can respond to you and evaluate the opportunity.',
      },
      {
        heading: 'Information we collect automatically',
        body: 'When you use our Services, we automatically collect certain information about your device and usage, including your IP address, browser type, operating system, referring URLs, pages viewed, time spent on pages, and other diagnostic data.',
      },
      {
        heading: 'Hardware and device data',
        body: 'When you deploy Aeros hardware, we may process data generated by those devices: imagery and computer-vision events from Aeros Sight cameras; identity, access, and presence events from Aeros Badge (via BLE and NFC); environmental and equipment telemetry from Aeros Sense sensors; and point-of-sale and operational data from Aeros Terminal. See the "Hardware, Cameras, and IoT Devices" section for how our responsibilities differ in these scenarios.',
      },
      {
        heading: 'AI inputs',
        body: 'When you use Aeros AI, we process the operational and account data you direct it to analyze in order to generate insights, reports, recommendations, and anomaly detection. We do not use your business data to train models for other customers without your explicit consent.',
      },
      {
        heading: 'Information from third parties',
        body: 'We may receive information about you from third-party services you connect to Aeros, such as payment processors, accounting software, logistics providers, or marketplace integrations. We only collect such information with your explicit authorization.',
      },
    ],
  },
  {
    title: '2. How We Use Your Information',
    content: [
      {
        heading: 'Providing and improving our services',
        body: 'We use your information to operate, maintain, and improve Aeros, including to process transactions, provide customer support, send service-related communications, and develop new features.',
      },
      {
        heading: 'Operating the marketplace',
        body: 'We use marketplace and transaction data to match buyers and sellers, surface relevant catalogs and quotes, process orders, coordinate fulfillment and shipping, calculate applicable taxes, and resolve disputes between participants.',
      },
      {
        heading: 'AI-powered insights',
        body: 'We use the data you direct to Aeros AI to generate the reports, recommendations, natural-language answers, and anomaly alerts you request, and to operate those features reliably and securely.',
      },
      {
        heading: 'Operating connected hardware',
        body: 'Where you deploy Aeros hardware, we use device data to operate the devices, deliver the analytics and dashboards you have configured, maintain device health and firmware, and provide support.',
      },
      {
        heading: 'Personalization',
        body: 'We use your information to personalize your experience, including tailoring content, recommendations, and AI-powered insights to your business context and usage patterns.',
      },
      {
        heading: 'Communications',
        body: 'With your consent where required, we may send you promotional communications about Aeros products, features, and events. You can opt out of marketing emails at any time by clicking "unsubscribe" in any email or contacting us directly.',
      },
      {
        heading: 'Legal and compliance',
        body: 'We may use your information to comply with applicable laws and regulations, enforce our terms of service, protect the rights and safety of Aeros and our users, and respond to lawful requests from public authorities.',
      },
    ],
  },
  {
    title: '3. How We Share Your Information',
    content: [
      {
        heading: 'Service providers',
        body: 'We share your information with third-party service providers who perform services on our behalf, such as cloud hosting, payment processing, analytics, and customer support. These providers are contractually obligated to use your information only as directed by us.',
      },
      {
        heading: 'Between marketplace participants',
        body: 'To complete a transaction, we share the information reasonably necessary between the buyer and seller involved — for example, business name, contact details, order contents, and shipping information. Aeros acts as an intermediary platform and is not itself a party to the underlying sale.',
      },
      {
        heading: 'Logistics and payment partners',
        body: 'We share order, shipping, and billing information with logistics carriers, fulfillment partners, and payment processors as needed to ship goods and settle payments connected to your transactions.',
      },
      {
        heading: 'Business transfers',
        body: 'If Aeros is involved in a merger, acquisition, or sale of assets, your information may be transferred as part of that transaction. We will notify you of any such change and any choices you may have.',
      },
      {
        heading: 'Legal requirements',
        body: 'We may disclose your information if required to do so by law or in response to valid legal process, including to meet national security or law enforcement requirements.',
      },
      {
        heading: 'With your consent',
        body: 'We may share your information for other purposes with your explicit consent.',
      },
    ],
  },
  {
    title: '4. Hardware, Cameras, and IoT Devices',
    content: [
      {
        heading: 'Sensitive data from connected devices',
        body: 'Aeros hardware can capture sensitive information about a physical environment — including video and imagery (Aeros Sight), identity and access events (Aeros Badge), and location, environmental, and equipment telemetry (Aeros Sense and Aeros Terminal). We apply heightened safeguards to this data and limit its use to operating the features you have enabled.',
      },
      {
        heading: 'Our role: controller vs. processor',
        body: 'When a business deploys Aeros hardware on its own premises, that business decides what is collected and why, and therefore acts as the data controller; Aeros processes that data on its behalf under a data processing agreement and uses it only to provide the Services. For your account, billing, and our own website data, Aeros acts as the controller.',
      },
      {
        heading: 'On-premises responsibilities',
        body: 'If you deploy cameras or wearables that capture data about your staff, customers, or visitors, you are responsible for providing any notices, signage, and consents required by applicable law in your jurisdiction. We provide configuration controls, retention settings, and access management to help you meet those obligations.',
      },
    ],
  },
  {
    title: '5. Data Retention',
    content: [
      {
        heading: 'Retention periods',
        body: 'We retain your personal information for as long as necessary to provide our Services, comply with our legal obligations, resolve disputes, and enforce our agreements. When we no longer need your information, we securely delete or anonymize it.',
      },
      {
        heading: 'Device data retention',
        body: 'Data captured by Aeros hardware is retained according to the retention period you configure for each device or deployment. Where you act as the controller, you may adjust or shorten these periods through your device settings.',
      },
      {
        heading: 'Account deletion',
        body: 'When you delete your account, we will delete or anonymize your personal information within 90 days, except where we are required to retain it for legal or compliance purposes.',
      },
    ],
  },
  {
    title: '6. Security',
    content: [
      {
        heading: 'Our security practices',
        body: 'We take the security of your information seriously. We use industry-standard encryption (TLS 1.3+) for data in transit, AES-256 encryption for data at rest, regular security audits, and strict access controls. Our infrastructure is hosted on SOC 2 Type II certified providers.',
      },
      {
        heading: 'Hardware and edge security',
        body: 'Aeros devices authenticate to our platform using per-device credentials, communicate over encrypted channels, and receive signed firmware updates. Where supported, sensitive processing such as computer vision is performed on the device (at the edge) to minimize the data transmitted off-site.',
      },
      {
        heading: 'Your responsibilities',
        body: 'You are responsible for maintaining the security of your account credentials. Please use a strong, unique password and enable two-factor authentication. Notify us immediately if you suspect unauthorized access to your account.',
      },
    ],
  },
  {
    title: '7. Your Rights and Choices',
    content: [
      {
        heading: 'Access and portability',
        body: 'You have the right to access the personal information we hold about you and to receive a copy of your data in a structured, machine-readable format.',
      },
      {
        heading: 'Correction and deletion',
        body: 'You may update or correct inaccurate personal information at any time through your account settings. You may also request deletion of your personal information, subject to certain legal exceptions.',
      },
      {
        heading: 'Objection and restriction',
        body: 'You have the right to object to or request restriction of certain processing of your personal information, including for direct marketing purposes.',
      },
      {
        heading: 'Exercising your rights',
        body: 'To exercise any of these rights, please contact us at privacy@aeros.io. We will respond to your request within 30 days. If you are a customer and your request concerns data for which a business acts as controller (for example, hardware deployed on their premises), we will refer you to that business.',
      },
    ],
  },
  {
    title: '8. Cookies and Tracking',
    content: [
      {
        heading: 'Types of cookies we use',
        body: 'We use essential cookies necessary for our Services to function, performance cookies to understand how our Services are used, and functional cookies to remember your preferences. We do not use third-party advertising cookies.',
      },
      {
        heading: 'Your cookie choices',
        body: 'You can control cookies through your browser settings. Disabling certain cookies may affect the functionality of our Services. For full details, see our Cookie Policy at /cookies.',
      },
    ],
  },
  {
    title: '9. International Data Transfers',
    content: [
      {
        heading: 'Cross-border transfers',
        body: 'Aeros operates globally and may transfer your information to countries other than your country of residence. Where we transfer data internationally, we rely on appropriate safeguards such as Standard Contractual Clauses approved by the European Commission, or other legally recognized mechanisms.',
      },
    ],
  },
  {
    title: '10. Children\'s Privacy',
    content: [
      {
        heading: 'Age restrictions',
        body: 'Our Services are not directed to individuals under the age of 18. We do not knowingly collect personal information from children. If you believe we have inadvertently collected information from a child, please contact us immediately and we will delete it.',
      },
    ],
  },
  {
    title: '11. Changes to This Policy',
    content: [
      {
        heading: 'Policy updates',
        body: 'We may update this Privacy Policy from time to time. We will notify you of material changes by posting the new policy on this page and updating the "Last updated" date. For significant changes, we will provide additional notice via email or a prominent notice on our platform.',
      },
    ],
  },
  {
    title: '12. Contact Us',
    content: [
      {
        heading: 'Get in touch',
        body: 'If you have questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact our Data Protection Officer at privacy@aeros.io. You can also write to us at one of the offices below.',
      },
      {
        heading: 'India (registered office)',
        body: 'Aeros Ventures Private Limited, 76/612, Motilal Nagar No. 1, Goregaon West, Mumbai 400104, India.',
      },
      {
        heading: 'United States',
        body: 'Office: 131 Continental Dr, Suite 305, Newark, DE 19713, USA. Mailing address: 2810 N Church St STE 88871, Wilmington, DE 19802, USA.',
      },
    ],
  },
]

export default function PrivacyPolicy() {
  return (
    <main className="min-h-screen bg-white">
      <Navbar />

      <section className="pt-32 pb-16 px-6 bg-bg-subtle border-b border-border-default">
        <div className="max-w-3xl mx-auto">
          <div className="text-[10px] font-mono uppercase tracking-widest text-fg-muted/60 mb-4">
            Legal
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-fg-primary tracking-tight mb-4">
            Privacy Policy
          </h1>
          <p className="text-fg-muted text-lg leading-relaxed mb-6">
            We are committed to protecting your personal information and being transparent about how we collect and use it.
          </p>
          <div className="flex flex-wrap gap-6 text-xs text-fg-muted/60 font-mono">
            <span>Last updated: June 4, 2026</span>
            <span>Effective: June 4, 2026</span>
          </div>
        </div>
      </section>

      <section className="py-16 px-6">
        <div className="max-w-3xl mx-auto">
          <div className="mb-12 p-6 rounded-2xl border border-border-default bg-bg-subtle">
            <p className="text-fg-primary-800 leading-relaxed text-[15px]">
              This Privacy Policy describes how Aeros Ventures Private Limited (&quot;Aeros&quot;, &quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) collects, uses, shares, and protects personal information when you use our marketplace, operating system, AI, hardware, and related products and services (&quot;Services&quot;). By using our Services, you agree to the collection and use of information in accordance with this policy.
            </p>
          </div>

          <div className="space-y-12">
            {sections.map((section) => (
              <div key={section.title}>
                <h2 className="text-xl font-bold text-fg-primary mb-6 pb-3 border-b border-border-default">
                  {section.title}
                </h2>
                <div className="space-y-6">
                  {section.content.map((item) => (
                    <div key={item.heading}>
                      <h3 className="text-[15px] font-semibold text-fg-primary mb-2">
                        {item.heading}
                      </h3>
                      <p className="text-fg-muted text-[15px] leading-relaxed">
                        {item.body}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          <div className="mt-16 pt-8 border-t border-border-default">
            <p className="text-fg-muted text-sm leading-relaxed">
              This policy applies to all Aeros products and services unless a separate privacy notice is provided. For questions, contact{' '}
              <a href="mailto:privacy@aeros.io" className="text-fg-primary underline hover:text-royal-600 transition-colors">
                privacy@aeros.io
              </a>.
            </p>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  )
}
